import { CardDetails } from "../config/type";

export const demoCards2: CardDetails[] = [
    {
      asset: "/asset/RcbPoster.png",
      QHead: "Will Bitcoin reach $50K by next month?",
      QBody: "Predict if the price of Bitcoin will hit $50,000 within the next month.",
      winProb: 60,
      lossProb: 40,
      category: "Crypto",
      expireTime: "2025-02-15T23:59:59Z",
      totalBets: 1200,
      yesPrice: 45,
      noPrice: 55,
      maxQuantity: 10,
    }
  ];
  
  export const demoCards: CardDetails[] = [
    {
        asset: "/asset/RcbPoster.png",
        QHead: "Will Tesla stock hit $900 this year?",
        QBody: "Elon Musk's plans might push Tesla stock to new highs.",
        winProb: 55,
        lossProb: 45,
        category: "Stocks",
        expireTime: "2025-12-31T23:59:59Z",
        totalBets: 1500,
        yesPrice: 50,
        noPrice: 50,
        maxQuantity: 75,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will Apple release AR glasses in 2025?",
        QBody: "Rumors suggest Apple is working on groundbreaking AR tech.",
        winProb: 70,
        lossProb: 30,
        category: "Tech",
        expireTime: "2025-07-01T23:59:59Z",
        totalBets: 950,
        yesPrice: 65,
        noPrice: 35,
        maxQuantity: 50,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will the S&P 500 index surpass 5000 points?",
        QBody: "The stock market has been volatile; will it achieve new highs?",
        winProb: 40,
        lossProb: 60,
        category: "Markets",
        expireTime: "2025-06-30T23:59:59Z",
        totalBets: 3000,
        yesPrice: 30,
        noPrice: 70,
        maxQuantity: 200,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will gold prices exceed $2000 per ounce?",
        QBody: "Inflation concerns might drive gold prices higher.",
        winProb: 65,
        lossProb: 35,
        category: "Commodities",
        expireTime: "2025-09-01T23:59:59Z",
        totalBets: 800,
        yesPrice: 55,
        noPrice: 45,
        maxQuantity: 150,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will a major bank announce bankruptcy?",
        QBody: "Economic challenges could lead to a major financial institution collapse.",
        winProb: 20,
        lossProb: 80,
        category: "Finance",
        expireTime: "2025-08-20T23:59:59Z",
        totalBets: 500,
        yesPrice: 20,
        noPrice: 80,
        maxQuantity: 300,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will oil prices drop below $60 per barrel?",
        QBody: "With production increasing, oil prices might fall.",
        winProb: 50,
        lossProb: 50,
        category: "Energy",
        expireTime: "2025-05-10T23:59:59Z",
        totalBets: 1400,
        yesPrice: 40,
        noPrice: 60,
        maxQuantity: 120,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will AI surpass human intelligence by 2030?",
        QBody: "Artificial Intelligence is progressing rapidly, but can it surpass humans?",
        winProb: 30,
        lossProb: 70,
        category: "AI",
        expireTime: "2029-12-31T23:59:59Z",
        totalBets: 2000,
        yesPrice: 25,
        noPrice: 75,
        maxQuantity: 500,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will the next iPhone have a foldable display?",
        QBody: "Foldable tech is trending; will Apple join the race?",
        winProb: 50,
        lossProb: 50,
        category: "Tech",
        expireTime: "2025-09-15T23:59:59Z",
        totalBets: 1800,
        yesPrice: 50,
        noPrice: 50,
        maxQuantity: 90,
      },
      {
        asset: "/asset/RcbPoster.png",
        QHead: "Will a major climate change policy be implemented?",
        QBody: "Governments are under pressure to take action on climate change.",
        winProb: 80,
        lossProb: 20,
        category: "Environment",
        expireTime: "2026-01-01T23:59:59Z",
        totalBets: 1600,
        yesPrice: 75,
        noPrice: 25,
        maxQuantity: 60,
      },
  ];
  